apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  name: {{ printf "%s-%s" "analysis" (toString .Values.analysisSuffix) }}
  namespace: default
  annotations:
    notifications.argoproj.io/subscribe.on-analysis-run-failed.github: ""
    notifications.argoproj.io/subscribe.on-analysis-run-success.github: ""
    notifications.argoproj.io/subscribe.on-analysis-run-running.github: ""
spec:
  args:
    - name: active-service
      value: api-user-active
    - name: preview-service
      value: api-user-preview
  metrics:
    - name: service-tester
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - image: busybox
                    command: ["/bin/sh"]
                    args:
                      - "-c"
                      - "sleep 30 && echo '{{`{{args.preview-service}}`}}' && sleep 30;exit 0;"
                    name: checker
                restartPolicy: Never
